baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Alison McDonald'
theme = 'alison-portfolio'


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
